openapi: 3.0.0
info:
  description: task-scheduler-client
  title: task-scheduler-client
  version: ^1.0.0
tags:
  - name: Executavel
paths:
  /executavel/{id}:
    get:
      operationId: getExecutavelPorId
      summary: Obtém um executável
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          $ref: '#/components/schemas/Executavel'
        '400':
          description: Requisição inválida
        '404':
          description: Nenhum cadastrado
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
  /executavel/list:
    get:
      operationId: getExecutaveis
      summary: Obtém uma lista dos executáveis disponíveis
      parameters:
        - in: query
          name: max
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: Listagem bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Executavel'
        '400':
          description: Requisição inválida
        '404':
          description: Nenhum tiss_version cadastrado
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
  /executavel/adicionar:
    post:
      operationId: adicionarExecutavel
      summary: Adicionar executável
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Executavel'
      responses:
        '200':
          description: OK
        '400':
          description: Requisição inválida
        '404':
          description: Nenhum tiss_version cadastrado
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
  /executavel/atualizar/{id}:
    post:
      operationId: atualizarExecutavel
      summary: Atualizar executável
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Executavel'
      responses:
        '200':
          description: OK
        '400':
          description: Requisição inválida
        '404':
          description: Nenhum tiss_version cadastrado
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
  /executavel/remover/{id}:
    delete:
      operationId: removerExecutavel
      summary: Remover executável
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
        '400':
          description: Requisição inválida
        '404':
          description: Nenhum
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
  /agendamento/list:
    get:
      operationId: getAgendamentos
      summary: Obtém uma lista dos agendamentos disponíveis
      parameters:
        - in: query
          name: max
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: Listagem bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Agendamento'
        '400':
          description: Requisição inválida
        '404':
          description: Nenhum agendamento encontrado
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
  /agendamento/adicionar:
    post:
      operationId: adicionarAgendamento
      summary: Adicionar agendamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Agendamento'
      responses:
        '200':
          description: OK
        '400':
          description: Requisição inválida
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
  /agendamento/remover/{id}:
    delete:
      operationId: removerAgendamento
      summary: Remover agendamento
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: OK
        '400':
          description: Requisição inválida
        '404':
          description: Nenhum
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
  /execucao/{id}:
    get:
      operationId: getExecucaoPorId
      summary: Obtém um execução
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          $ref: '#/components/schemas/Execucao'
        '400':
          description: Requisição inválida
        '404':
          description: Nenhum cadastrado
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
  /execucao/list:
    get:
      operationId: getExecucoes
      summary: Obtém uma lista das execuções
      parameters:
        - in: query
          name: max
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: Listagem bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Execucao'
        '400':
          description: Requisição inválida
        '404':
          description: Nenhum cadastrado
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
  /execucao/adicionar:
    post:
      operationId: adicionarExecucao
      summary: Adicionar execução
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Executavel'
      responses:
        '200':
          description: OK
        '400':
          description: Requisição inválida
        '404':
          description: Nenhum cadastrado
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
  /execucao/parar:
    post:
      operationId: pararExecucao
      summary: Parar execução
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Execucao'
      responses:
        '200':
          description: OK
        '400':
          description: Requisição inválida
        '404':
          description: Não cadastrado
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
  /execucao/reexecutar:
    post:
      operationId: reexecutarExecucao
      summary: Reexecutar execução
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Execucao'
      responses:
        '200':
          description: OK
        '400':
          description: Requisição inválida
        '404':
          description: Não cadastrado
        '500':
          description: Ocorreu um erro inesperado.
      security:
        - jwt: [ ]
servers:
  - url: 'http://localhost:8080/'
components:
  securitySchemes:
    jwt:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://localhost:8080/login'
          scopes:
            read: Grants read access
            write: Grants write access
  schemas:
    Parametro:
      type: object
      properties:
        nome:
          type: string
        tipo:
          type: string
    Executavel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        titulo:
          type: string
        descricao:
          type: string
        classeExecutavel:
          type: string
        dataCriacao:
          type: string
        parametros:
          type: array
          items:
            $ref: '#/components/schemas/Parametro'
    Agendamento:
      type: object
      properties:
        id:
          type: integer
          format: int64
        dataExecucao:
          type: string
          format: date
        horaExecucao:
          type: string
        executavel:
          $ref: '#/components/schemas/Executavel'
    Execucao:
      type: object
      properties:
        id:
          type: integer
          format: int64
        data:
          type: string
          format: date-time
        progresso:
          type: number
        manual:
          type: boolean
        status:
          $ref: '#/components/schemas/StatusExecucao'
        executavel:
          $ref: '#/components/schemas/Executavel'
        eventos:
          type: array
          items:
            $ref: '#/components/schemas/Evento'
    Evento:
      type: object
      properties:
        descricao:
          type: string
        data:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/StatusEvento'
    StatusExecucao:
      type: string
      enum:
        - Concluido
        - EmExecucao
        - Erro
    StatusEvento:
      type: string
      enum:
        - Sucesso
        - Advertencia
        - Erro
